---
- name: Check Shorewall6
  listen: check shorewall6
  ansible.builtin.command: shorewall6 check
  ignore_errors: "{{ ansible_check_mode }}"
  changed_when: false

- name: Restart Shorewall6
  listen: restart shorewall6
  ansible.builtin.service:
    name: shorewall6
    state: "{{ shorewall6_restart_handler_state }}"
  when: shorewall6_service_state == "started"
  ignore_errors: "{{ ansible_check_mode }}"
