- name: Check and restart Shorewall6
  listen: check and restart shorewall6
  command: shorewall6 check
  notify: restart shorewall6

- name: Restart Shorewall6
  listen: restart shorewall6
  service:
    name: shorewall6
    state: restarted
  when: shorewall6_service_state == "started"
