---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure Shorewall6 is installed
      ansible.builtin.stat:
        path: "/usr/sbin/shorewall6"
      register: result
      changed_when: false
      failed_when: result.stat.islnk is not defined or not result.stat.islnk

    - name: Ensure permissions on params configuration file are correct
      ansible.builtin.stat:
        path: "/etc/shorewall6/params"
      register: shorewall6_params
      failed_when: shorewall6_params.stat.mode != "0640"

    - name: Ensure dynamic blacklist support is set correctly
      ansible.builtin.command:
        argv:
          - grep
          - -q
          - ^DYNAMIC_BLACKLIST=ipset-only,disconnect
          - /etc/shorewall6/shorewall6.conf
      changed_when: false

    - name: Ensure rule from shorewall6_group_rules is present
      ansible.builtin.command:
        argv:
          - grep
          - -q
          - ^HTTPS(ACCEPT) net $FW
          - /etc/shorewall6/rules
      changed_when: false

    - name: Ensure rule from shorewall6_host_rules is present
      ansible.builtin.command:
        argv:
          - grep
          - -q
          - ^IMAP(ACCEPT) net $FW
          - /etc/shorewall6/rules
      changed_when: false

    - name: Ensure skipped rule from shorewall_host_rules is not present
      ansible.builtin.command:
        argv:
          - grep
          - -q
          - ^SMTP(ACCEPT) net $FW
          - /etc/shorewall6/rules
      register: grep
      changed_when: false
      failed_when: not grep.failed

    - name: Ensure non-skipped rule from shorewall_host_rules is present
      ansible.builtin.command:
        argv:
          - grep
          - -q
          - ^DNS(REJECT) net:2606:4700:4700::1111 $FW
          - /etc/shorewall6/rules
      changed_when: false

    - name: Ensure nested list in shorewall_group_params is flattened
      command:
        argv:
          - grep
          - -q
          - "^NESTED_LIST=2606:4700:4700::1111,2606:4700:4700::1001,2001:4860:4860::8888"
          - /etc/shorewall6/params
      changed_when: false

    - name: Ensure shorewall_params vars are merged
      command:
        argv:
          - grep
          - -q
          - "^LOCALHOST=::1"
          - /etc/shorewall6/params
      changed_when: false
